version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: todo
      MONGO_INITDB_ROOT_USERNAME: todouser
      MONGO_INITDB_ROOT_PASSWORD: todopass
    ports:
      - "27017:27017"
  app:
    build: ./
    environment:
      MONGODB_HOST: mongo
      MONGODB_DATABASE: todo
      MONGODB_USERNAME: todouser
      MONGODB_PASSWORD: todopass
    ports:
      - "8080:80"
    depends_on:
      - mongo
      